// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NoVar
{
    internal sealed partial class Vsix
    {
        public const string Id = "NoVar.0c14e1a6-58d7-4ee5-803b-c41e0f7145f8";
        public const string Name = "NoVar";
        public const string Description = @"NoVar is a Visual Studio extension designed to improve code readability by replacing `var` declarations with explicit types. This extension provides two main features that allow users to replace `var` based on their specific needs.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Prabhath Kiran Atmakuri";
        public const string Tags = "";
    }
}
