// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NoVar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NoVarString = "64ed5da6-8974-4cef-9d92-87ab8f9a2e2c";
        public static Guid NoVar = new Guid(NoVarString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NoVarMenuGroup = 0x0001;
        public const int ReplaceAll = 0x0100;
        public const int ReplaceNotNewVars = 0x0200;
    }
}