# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Build"
permissions:
  actions: write
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1
    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
        
    - name: Restore
      run: dotnet restore NoVarExtension.sln

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: msbuild NoVarExtension.sln /property:Configuration=Release /t:Rebuild
